INSERT OR IGNORE INTO plan_seasons (
    season_id,
    season_code,
    season_name,
    start_date,
    end_date,
    status,
    notes
) VALUES (
    2026,
    '2026',
    'Temporada 2026',
    '2026-05-04',
    '2026-12-31',
    'active',
    'Temporada orientada a reconstruccion solida, base aerobica y cierre sin deuda fisiologica.'
);

INSERT OR IGNORE INTO plan_user_profiles (
    season_id,
    alias,
    age_years,
    height_cm,
    reference_weight_kg,
    target_weight_kg,
    current_form,
    baseline_fatigue,
    current_strength,
    recovery_profile,
    primary_sport,
    secondary_sports,
    best_tolerated_training,
    worst_tolerated_training,
    availability_notes,
    support_routine
) VALUES (
    2026,
    NULL,
    52,
    187,
    92,
    80,
    'Baja forma',
    'Baja',
    'Poca fuerza',
    'Mala recuperacion tras esfuerzos intensos de un dia para otro',
    'Bicicleta',
    'Monte, carrera, paseo',
    'Bicicleta',
    'Carrera intensa, series largas en bici y repeticiones cortas intensas',
    'Alta disponibilidad: hasta 7 dias por semana, 2 horas entre semana y 4-6 horas en fin de semana',
    'Rutina matinal diaria de 20 minutos de activacion ligera y 20 minutos de flexibilidad, ajustable a la baja si interfiere con la recuperacion'
);

INSERT OR IGNORE INTO plan_macro_cycles (
    macro_id,
    season_id,
    title,
    objective_statement,
    context_summary,
    priorities,
    progression_rules,
    weight_rules,
    success_criteria,
    prudence_criteria,
    closing_rule,
    markdown_path
) VALUES (
    1,
    2026,
    'Planificacion Macro 2026',
    'En 2026 la prioridad es volver a entrenar bien tras el paron y asentar una base solida y sostenible.',
    'Reinicio del entrenamiento estructurado, base aerobica presente pero incompleta, foco principal en bicicleta, buena disponibilidad y recuperacion limitada tras intensidad.',
    '1) Normalizar semanas consistentes. 2) Consolidar tolerancia al volumen aerobico basico. 3) Reducir peso de forma gradual. 4) Mantener fuerza minima eficaz. 5) Introducir trabajo mas intencional solo cuando la semana normal ya sea estable. 6) Progresar por acumulacion aerobica y repetibilidad antes que por intensidad. 7) Usar flexibilidad de medios y horarios para sostener adherencia.',
    'Progresar solo si la semana previa deja margen real, priorizar tiempo aerobico antes que intensidad, tocar una sola variable cada vez y reservar la intensidad para momentos con recuperacion normal.',
    'Bajar peso bien y no rapido, evitando comprometer energia disponible, recuperacion o fuerza minima.',
    'Semanas repetibles sin fatiga arrastrada, bicicleta como actividad central normal, indice aerobico estable o mejor, peso a la baja sin deterioro, fuerza mantenida, rutina matinal y recuperacion sosteniendo el proceso.',
    'No progresar con pesadez persistente, mal descanso, baja motivacion, semanas demasiado costosas, rendimiento a la baja o mala recuperacion tras sesiones intensas.',
    'Cerrar noviembre y diciembre conservando actividad y base, llegando al siguiente ciclo con ganas de construir y no de recuperarse.',
    '2026/Macro.md'
);

INSERT OR IGNORE INTO plan_meso_blocks (
    block_id, season_id, block_code, block_name, phase_name, sequence_order, start_date, end_date,
    duration_weeks_min, duration_weeks_max, objective_primary, objective_secondary, objective_complementary,
    entry_criteria, exit_criteria, key_risks, micro_pattern, progression_logic, markdown_path
) VALUES
(
    1, 2026, 'B1', 'Reconstruccion solida', 'Reconstruccion inicial', 1, '2026-05-04', '2026-06-14',
    4, 6,
    'Volver a ser entrenable de forma estable.',
    'Recuperar normalidad en la bicicleta sin fatiga arrastrada.',
    'Iniciar una tendencia de peso compatible con entrenar bien.',
    'Reinicio del trabajo estructurado, base aerobica poco asentada y necesidad de priorizar adherencia antes que intensidad.',
    'Semanas sin deuda, salida larga controlada tolerada, fuerza minima integrada y sensacion de semana tipo asumible.',
    'Subir demasiado pronto volumen o exigencia, confundir ganas con capacidad real y forzar perdida de peso a costa de recuperacion.',
    'Semanas con bici como eje, fuerza minima eficaz, paseo y movilidad como soporte, intensidad contenida.',
    'Progresion por tiempo aerobico util con una semana de absorcion intermedia y cierre de validacion.',
    '2026/Bloques/B1-Reconstruccion-solida/README.md'
),
(
    2, 2026, 'B2', 'Construccion aerobica extensiva I', 'Construccion aerobica principal', 2, '2026-06-15', '2026-07-19',
    4, 5,
    'Aumentar el tiempo aerobico util sin romper continuidad.',
    'Consolidar la bicicleta como medio principal de desarrollo.',
    'Sostener tendencia de peso y fuerza minima sin interferencia.',
    'Semana tipo ya asumible tras B1, salida larga controlada tolerada y fatiga basal estable.',
    'Mas tiempo aerobico semanal tolerado, frecuencia alta sostenible y salida larga mejor integrada.',
    'Progresar por intensidad, dispersar el foco por exceso de variedad y perder sensacion de control.',
    'Semanas de acumulacion aerobica controlada con proteccion clara de la recuperacion.',
    'Crecimiento de tiempo aerobico y frecuencia, no de dureza.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/README.md'
),
(
    3, 2026, 'B3', 'Consolidacion y absorcion', 'Construccion aerobica principal', 3, '2026-07-20', '2026-08-09',
    3, 4,
    'Estabilizar lo construido y bajar la presion de progreso.',
    'Confirmar que la semana sigue siendo repetible con buena sensacion.',
    'Mantener peso y fuerza en una zona compatible con entrenar bien.',
    'Acumulacion aerobica relevante en B2 y necesidad de estabilizacion.',
    'Frescura recuperada, carga absorbida y disposicion para un segundo bloque de construccion.',
    'Mantener demasiada dureza o bajar tanto la carga que se pierda continuidad.',
    'Semanas de alivio relativo y consolidacion sin perder estructura.',
    'Reducir presion sin dejar de estimular.',
    '2026/Bloques/B3-Consolidacion-y-absorcion/README.md'
),
(
    4, 2026, 'B4', 'Construccion aerobica extensiva II', 'Construccion aerobica principal', 4, '2026-08-10', '2026-09-13',
    4, 5,
    'Ampliar de nuevo la base aerobica por duracion o densidad.',
    'Mejorar tolerancia a semanas llenas con la bicicleta como eje central.',
    'Sostener fuerza minima y tendencia de peso con buena recuperacion.',
    'B3 completado con buena absorcion y semana tipo estable.',
    'Mas densidad o duracion absorbida respecto a B2 y salida larga consolidada.',
    'Repetir B2 sin margen suficiente, introducir intensidad por impaciencia o acumular cansancio silencioso.',
    'Semanas con segundo empuje aerobico y control estricto de la recuperacion.',
    'Crecer por densidad o duracion manteniendo intensidad contenida.',
    '2026/Bloques/B4-Construccion-aerobica-extensiva-II/README.md'
),
(
    5, 2026, 'B5', 'Consolidacion funcional', 'Consolidacion y cierre', 5, '2026-09-14', '2026-10-18',
    4, 4,
    'Sostener la base aerobica sin necesidad de seguir empujando volumen.',
    'Mantener fuerza minima eficaz y valorar algun estimulo mas intencional solo si la recuperacion lo permite.',
    'Consolidar una sensacion de normalidad entrenando.',
    'B4 absorbido sin deuda clara y base aerobica util y repetible.',
    'La base se sostiene sin esfuerzo excesivo y el usuario llega al cierre del ano con margen.',
    'Abrir intensidad demasiado pronto o descuidar la fuerza minima.',
    'Semanas de mantenimiento funcional con margen y lectura de tolerancia.',
    'Sostener la base y abrir la puerta a algun estimulo mas intencional solo si no rompe continuidad.',
    '2026/Bloques/B5-Consolidacion-funcional/README.md'
),
(
    6, 2026, 'B6', 'Cierre util y transicion', 'Consolidacion y cierre', 6, '2026-11-01', '2026-12-31',
    4, 6,
    'Mantener actividad y base sin presion de seguir construyendo.',
    'Conservar fuerza minima y rutina suficiente para no perder normalidad.',
    'Llegar al siguiente ciclo con ganas de construir, no de recuperarse.',
    'B5 completado con sensacion de control y necesidad de proteger cierre del ano.',
    'Actividad mantenida sin tension, base conservada y descanso acumulado razonable.',
    'Dejarse caer demasiado, mantener inercia de construccion o llegar con cansancio escondido.',
    'Semanas de mantenimiento ligero y flexible.',
    'Bajar presion estrategicamente sin perder continuidad.',
    '2026/Bloques/B6-Cierre-util-y-transicion/README.md'
);

INSERT OR IGNORE INTO plan_micro_weeks (
    week_id, block_id, week_code, sequence_in_block, start_date, end_date, week_role, entry_state,
    objective_primary, objective_secondary, key_risk, weight_goal, target_volume_hours_min, target_volume_hours_max,
    key_days, support_days, closure_rule, markdown_path
) VALUES
(
    101, 1, 'Semana-01', 1, '2026-05-04', '2026-05-10', 'Introductoria',
    'Reinicio del trabajo estructurado con base aerobica presente y adaptacion todavia incompleta.',
    'Reactivar la rutina sin generar deuda y completar una salida larga controlada.',
    'Introducir la semana tipo y sostener la fuerza basica sin interferencia.',
    'Exceso de entusiasmo al principio del bloque.',
    'Empezar a ordenar habitos y abrir una tendencia descendente sin forzar.',
    7.0, 8.0,
    '1 salida larga controlada.',
    'Rodajes suaves, fuerza minima eficaz, paseo y movilidad.',
    'Pasar a una segunda semana similar o ajustar si la carga ya resulta alta.',
    '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'
),
(
    102, 1, 'Semana-02', 2, '2026-05-11', '2026-05-17', 'Continuidad',
    'Primera semana completada y necesidad de validar que la estructura se puede repetir.',
    'Repetir frecuencia y ampliar ligeramente el tiempo aerobico total.',
    'Consolidar la bicicleta como eje central y sostener la fuerza minima.',
    'Subir demasiado rapido tras una buena primera semana.',
    'Mantener una inercia ordenada sin tension adicional.',
    8.0, 9.0,
    '2 rodajes aerobicos y 1 salida larga controlada.',
    'Fuerza minima, paseo y movilidad.',
    'Confirmar si ya existe una semana tipo basica o si todavia hace falta contencion.',
    '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'
),
(
    103, 1, 'Semana-03', 3, '2026-05-18', '2026-05-24', 'Progresion suave',
    'Dos semanas encadenadas y primera base de rutina establecida.',
    'Aumentar el tiempo aerobico util y consolidar la semana de 6 dias.',
    'Introducir la salida de referencia aerobica en formato sencillo.',
    'Meter demasiada densidad aprovechando la alta disponibilidad.',
    'Seguir siendo compatible con buena energia para entrenar.',
    9.0, 10.0,
    '1 salida de referencia Z2 y 1 salida larga controlada.',
    'Fuerza minima, paseo y un dia muy facil.',
    'Bajar carga total y consolidar aunque la semana haya salido bien.',
    '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'
),
(
    104, 1, 'Semana-04', 4, '2026-05-25', '2026-05-31', 'Estabilizacion',
    'Tres semanas de acumulacion suave y necesidad de absorber para seguir progresando.',
    'Reducir ligeramente el volumen manteniendo estructura y frecuencia.',
    'Confirmar que la fuerza minima y la bici siguen conviviendo bien.',
    'Convertir una semana de consolidacion en otra semana de empuje.',
    'Sostener normalidad, no acelerar nada.',
    7.0, 8.0,
    '2 dias aerobicos medios y 1 salida larga algo mas corta.',
    'Fuerza minima muy controlada, paseo y movilidad.',
    'Volver a crecer solo si reaparece sensacion clara de margen.',
    '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'
),
(
    105, 1, 'Semana-05', 5, '2026-06-01', '2026-06-07', 'Construccion',
    'Carga absorbida y disposicion para un segundo empuje controlado.',
    'Volver a subir tiempo aerobico util tras la semana de absorcion.',
    'Reforzar la salida larga de 3 horas como elemento normal del bloque.',
    'Que la ambicion supere la absorcion real de la semana 04.',
    'Seguir bajando bien, no rapido.',
    9.5, 10.5,
    '2 dias aerobicos, 1 fuerza minima y 1 salida larga asentada.',
    'Paseo, movilidad y un dia muy facil.',
    'No subir mas; usar la semana 06 para validar, no para forzar.',
    '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'
),
(
    106, 1, 'Semana-06', 6, '2026-06-08', '2026-06-14', 'Validacion',
    'Bloque casi consolidado y necesidad de comprobar que la semana tipo ya es repetible.',
    'Repetir una semana tipo solida con buena sensacion global.',
    'Comprobar que la referencia aerobica y la salida larga encajan dentro de una semana completa.',
    'Intentar cerrar el bloque con un exceso final de carga.',
    'Mantener el proceso ordenado sin interferir con la salida del bloque.',
    9.0, 10.0,
    '1 referencia aerobica, 1 fuerza minima y 1 salida larga controlada.',
    'Paseo, un dia muy facil y actividad complementaria suave.',
    'Pasar a B2 solo si la base ya es util y repetible; si no, prolongar B1 una semana mas.',
    '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'
);

INSERT OR IGNORE INTO meta_markdown_views (season_id, entity_type, entity_id, file_path, role, sync_status, notes) VALUES
(2026, 'season', 2026, '2026/README.md', 'human-view', 'manual', 'Indice humano de la temporada 2026.'),
(2026, 'profile', 2026, '2026/Ficha-usuario.md', 'human-view', 'manual', 'Vista humana del perfil de usuario de 2026.'),
(2026, 'macro', 1, '2026/Macro.md', 'human-view', 'manual', 'Vista humana del macro 2026.'),
(2026, 'meso_block', 1, '2026/Bloques/B1-Reconstruccion-solida/README.md', 'human-view', 'manual', 'Vista humana de B1.'),
(2026, 'meso_block', 2, '2026/Bloques/B2-Construccion-aerobica-extensiva-I/README.md', 'human-view', 'manual', 'Vista humana de B2.'),
(2026, 'meso_block', 3, '2026/Bloques/B3-Consolidacion-y-absorcion/README.md', 'human-view', 'manual', 'Vista humana de B3.'),
(2026, 'meso_block', 4, '2026/Bloques/B4-Construccion-aerobica-extensiva-II/README.md', 'human-view', 'manual', 'Vista humana de B4.'),
(2026, 'meso_block', 5, '2026/Bloques/B5-Consolidacion-funcional/README.md', 'human-view', 'manual', 'Vista humana de B5.'),
(2026, 'meso_block', 6, '2026/Bloques/B6-Cierre-util-y-transicion/README.md', 'human-view', 'manual', 'Vista humana de B6.');

INSERT OR IGNORE INTO plan_planned_sessions (
    planned_session_id, week_id, session_date, day_name, sequence_in_week, planned_type, objective,
    primary_session, complementary_session, notes, is_key_session, intensity_class, duration_min, duration_max,
    adjustment_rule, markdown_path
) VALUES
(10101, 101, '2026-05-04', 'Lunes', 1, 'activacion', 'Abrir la semana con activacion suave y sin fatiga.', 'Paseo 45-60 minutos o descanso activo.', 'Movilidad general 10-15 minutos.', 'Si hay sensacion de pesadez, convertir el dia en descanso completo.', 0, 'muy suave', 45, 60, 'Reducir a descanso completo si hay pesadez.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10102, 101, '2026-05-05', 'Martes', 2, 'bicicleta-z2', 'Recuperar sensacion de trabajo aerobico estructurado.', 'Bicicleta Z2 75-90 minutos, estable y sin apretar.', '4-6 aceleraciones muy cortas de cadencia.', 'Evitar convertir la sesion en tempo o series encubiertas.', 0, 'suave', 75, 90, 'Mantener todo en Z2 real.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10103, 101, '2026-05-06', 'Miercoles', 3, 'fuerza', 'Introducir fuerza minima sin interferencia.', 'Rutina base de fuerza 30-40 minutos con cargas comodas.', 'Paseo suave 20-30 minutos opcional.', 'Cortar antes de notar fatiga residual para el dia siguiente.', 0, 'moderada', 30, 40, 'Reducir volumen si deja fatiga residual.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10104, 101, '2026-05-07', 'Jueves', 4, 'bicicleta-z2', 'Sumar otro dia aerobico util con control.', 'Bicicleta Z2 60-75 minutos.', 'Movilidad o core suave 10 minutos.', 'Dia deliberadamente facil.', 0, 'suave', 60, 75, 'Quedarse corto antes que dejar deuda.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10105, 101, '2026-05-08', 'Viernes', 5, 'recuperacion', 'Llegar fresco al fin de semana.', 'Descanso activo o paseo de 45 minutos.', 'Estiramientos suaves o movilidad 10 minutos.', 'No anadir carga aunque el dia parezca facil.', 0, 'muy suave', 45, 45, 'Mantener dia facil incluso si hay frescura.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10106, 101, '2026-05-09', 'Sabado', 6, 'salida-larga', 'Completar la primera salida larga controlada del bloque.', 'Bicicleta 2h15-2h30 en Z2 comoda.', 'Nutricion e hidratacion ordenadas durante la salida.', 'Debe terminar con sensacion de que aun quedaba margen.', 1, 'suave', 135, 150, 'Recortar si hay señales de deuda temprana.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10107, 101, '2026-05-10', 'Domingo', 7, 'complementaria', 'Cerrar la semana soltando y comprobando recuperacion.', 'Paseo largo, monte suave o bicicleta muy facil 45-75 minutos.', 'Revision rapida de sensaciones, peso y fatiga.', 'Si el sabado deja carga alta, reducir claramente este dia.', 0, 'muy suave', 45, 75, 'Bajar a paseo suave si el sabado pesa.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-01/README.md'),
(10201, 102, '2026-05-11', 'Lunes', 1, 'activacion', 'Recuperar y preparar una semana parecida a la anterior.', 'Paseo 45-60 minutos o descanso activo.', 'Movilidad 10-15 minutos.', 'Dia de control, no de carga.', 0, 'muy suave', 45, 60, 'Mantener facil.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10202, 102, '2026-05-12', 'Martes', 2, 'bicicleta-z2', 'Sumar tiempo aerobico estable.', 'Bicicleta Z2 90 minutos.', '4-6 aceleraciones de cadencia de 10-15 segundos.', 'Mantener pulso y sensacion claramente aerobicos.', 0, 'suave', 90, 90, 'No subir intensidad.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10203, 102, '2026-05-13', 'Miercoles', 3, 'fuerza', 'Sostener fuerza minima eficaz.', 'Rutina base de fuerza 35-45 minutos.', 'Paseo suave 20-30 minutos opcional.', 'Evitar agujetas que condicionen jueves o sabado.', 0, 'moderada', 35, 45, 'Reducir si deja fatiga >24h.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10204, 102, '2026-05-14', 'Jueves', 4, 'bicicleta-z2', 'Repetir un segundo dia aerobico util.', 'Bicicleta Z2 75-90 minutos.', 'Movilidad o core suave 10 minutos.', 'Si hay fatiga de piernas, quedarse en el rango bajo.', 0, 'suave', 75, 90, 'Usar el rango bajo si pesa la fuerza.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10205, 102, '2026-05-15', 'Viernes', 5, 'recuperacion', 'Proteger la salida larga.', 'Descanso activo o bicicleta muy suave 45 minutos.', 'Estiramientos suaves.', 'No anadir intensidad por sensacion de frescura.', 0, 'muy suave', 45, 45, 'No convertirlo en dia de carga.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10206, 102, '2026-05-16', 'Sabado', 6, 'salida-larga', 'Ampliar ligeramente la salida larga.', 'Bicicleta 2h30-2h45 en Z2 controlada.', 'Nutricion e hidratacion desde el inicio.', 'Terminar con sensacion de control y buena tecnica.', 1, 'suave', 150, 165, 'Recortar si la semana se siente cara.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10207, 102, '2026-05-17', 'Domingo', 7, 'complementaria', 'Sumar actividad sin romper recuperacion.', 'Monte suave, paseo largo o bicicleta facil 60-90 minutos.', 'Revision de sensaciones y peso.', 'Si el sabado fue exigente, hacer solo paseo suave.', 0, 'muy suave', 60, 90, 'Reducir a paseo si el sabado pesa.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-02/README.md'),
(10301, 103, '2026-05-18', 'Lunes', 1, 'activacion', 'Abrir la semana con soltura.', 'Paseo 45-60 minutos.', 'Movilidad 10-15 minutos.', 'Mantener el dia facil aunque no haya fatiga.', 0, 'muy suave', 45, 60, 'No anadir carga por sentirse bien.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10302, 103, '2026-05-19', 'Martes', 2, 'referencia-aerobica', 'Obtener una referencia aerobica comparable.', 'Bicicleta Z2 estable 60-90 minutos en recorrido o formato repetible.', 'Registrar potencia media, frecuencia cardiaca media y sensacion.', 'Evitar condiciones que distorsionen la comparacion.', 1, 'suave', 60, 90, 'Priorizar comparabilidad frente a rendimiento.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10303, 103, '2026-05-20', 'Miercoles', 3, 'fuerza', 'Mantener fuerza minima y soporte general.', 'Rutina base de fuerza 35-45 minutos.', 'Paseo suave 20-30 minutos opcional.', 'Cargas comodas y tecnica limpia.', 0, 'moderada', 35, 45, 'Reducir si interfiere con jueves.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10304, 103, '2026-05-21', 'Jueves', 4, 'bicicleta-z2', 'Sumar otro dia aerobico util.', 'Bicicleta Z2 90 minutos.', 'Core o movilidad 10 minutos.', 'Dia de construccion tranquila.', 0, 'suave', 90, 90, 'Mantener todo claramente aerobico.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10305, 103, '2026-05-22', 'Viernes', 5, 'recuperacion', 'Llegar al fin de semana con margen.', 'Bicicleta muy facil 45-60 minutos o paseo.', 'Estiramientos suaves.', 'El objetivo es soltar, no acumular.', 0, 'muy suave', 45, 60, 'Reducir a paseo si se nota carga.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10306, 103, '2026-05-23', 'Sabado', 6, 'salida-larga', 'Consolidar la salida larga base del bloque.', 'Bicicleta 2h45-3h en Z2 controlada.', 'Alimentacion e hidratacion estables.', 'Debe parecer sostenible, no heroica.', 1, 'suave', 165, 180, 'Recortar si se vuelve heroica.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10307, 103, '2026-05-24', 'Domingo', 7, 'complementaria', 'Cerrar con actividad complementaria de bajo coste.', 'Monte suave, paseo largo o bicicleta facil 75-90 minutos.', 'Revision de datos de la semana.', 'Si el sabado dejo mas carga de la deseada, bajar a paseo suave.', 0, 'muy suave', 75, 90, 'Reducir si hay deuda del sabado.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-03/README.md'),
(10401, 104, '2026-05-25', 'Lunes', 1, 'activacion', 'Descanso util y absorcion.', 'Paseo 45-60 minutos o descanso activo.', 'Movilidad 10-15 minutos.', 'Dia de descarga real.', 0, 'muy suave', 45, 60, 'Descanso completo si hace falta.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10402, 104, '2026-05-26', 'Martes', 2, 'bicicleta-z2', 'Sostener el gesto aerobico sin exigir.', 'Bicicleta Z2 75 minutos.', '4 aceleraciones suaves de cadencia.', 'La sensacion de facilidad es el criterio principal.', 0, 'suave', 75, 75, 'Reducir si no se siente facil.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10403, 104, '2026-05-27', 'Miercoles', 3, 'fuerza', 'Mantener fuerza minima con menos carga.', 'Rutina base de fuerza 25-35 minutos.', 'Paseo opcional 20 minutos.', 'Reducir volumen respecto a semanas 02-03.', 0, 'suave', 25, 35, 'Mantener muy contenida.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10404, 104, '2026-05-28', 'Jueves', 4, 'bicicleta-z2', 'Repetir un dia aerobico estable y corto.', 'Bicicleta Z2 60-75 minutos.', 'Movilidad o core muy suave.', 'Si hay molestias o cansancio, recortar sin problema.', 0, 'suave', 60, 75, 'Recortar sin problema si no hay frescura.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10405, 104, '2026-05-29', 'Viernes', 5, 'recuperacion', 'Despejar antes del fin de semana.', 'Descanso activo o paseo 45 minutos.', 'Estiramientos suaves.', 'Dia deliberadamente facil.', 0, 'muy suave', 45, 45, 'No usar para compensar.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10406, 104, '2026-05-30', 'Sabado', 6, 'salida-larga', 'Mantener la salida larga con menor coste.', 'Bicicleta 2h15-2h30 en Z2.', 'Nutricion e hidratacion normales.', 'Debe dejar mejores sensaciones que la semana 03.', 1, 'suave', 135, 150, 'Mantener sensacion de facilidad creciente.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10407, 104, '2026-05-31', 'Domingo', 7, 'complementaria', 'Cerrar la semana con soltura.', 'Paseo largo, monte suave o bicicleta facil 45-60 minutos.', 'Revision de sensaciones generales.', 'Si aparece cansancio, dejar solo paseo.', 0, 'muy suave', 45, 60, 'Simplificar si hay cansancio.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-04/README.md'),
(10501, 105, '2026-06-01', 'Lunes', 1, 'activacion', 'Preparar una semana de nuevo crecimiento.', 'Paseo 45-60 minutos.', 'Movilidad 10-15 minutos.', 'El dia facil sigue siendo obligatorio.', 0, 'muy suave', 45, 60, 'Mantener siempre facil.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10502, 105, '2026-06-02', 'Martes', 2, 'bicicleta-z2', 'Sumar carga aerobica util.', 'Bicicleta Z2 90-105 minutos.', '4-6 aceleraciones de cadencia muy cortas.', 'Mantener control absoluto del esfuerzo.', 0, 'suave', 90, 105, 'No salir de control aerobico.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10503, 105, '2026-06-03', 'Miercoles', 3, 'fuerza', 'Mantener fuerza minima eficaz.', 'Rutina base de fuerza 35-45 minutos.', 'Paseo suave 20-30 minutos opcional.', 'Sin buscar progresos agresivos en cargas.', 0, 'moderada', 35, 45, 'Reducir si la fatiga sube.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10504, 105, '2026-06-04', 'Jueves', 4, 'bicicleta-z2', 'Reforzar la semana tipo con otro dia aerobico estable.', 'Bicicleta Z2 90 minutos.', 'Core suave o movilidad.', 'Si la fuerza pesa demasiado, recortar a 75 minutos.', 0, 'suave', 90, 90, 'Bajar a 75 si pesa la fuerza.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10505, 105, '2026-06-05', 'Viernes', 5, 'recuperacion', 'Proteger la salida larga y llegar suelto.', 'Bicicleta muy facil 45-60 minutos o paseo.', 'Estiramientos suaves.', 'Nada que suba la fatiga sistemica.', 0, 'muy suave', 45, 60, 'Mantener muy facil.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10506, 105, '2026-06-06', 'Sabado', 6, 'salida-larga', 'Normalizar la salida larga de 3 horas.', 'Bicicleta 3 horas en Z2 estable.', 'Alimentacion, bebida y ritmo bien ordenados.', 'La salida debe parecer ya parte natural de la semana.', 1, 'suave', 180, 180, 'Recortar si no se integra bien.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10507, 105, '2026-06-07', 'Domingo', 7, 'complementaria', 'Mantener actividad sin perder recuperacion.', 'Monte suave, paseo largo o bicicleta facil 60-90 minutos.', 'Revision de peso, sensacion y carga.', 'Si el sabado fue mas exigente de lo previsto, hacer solo paseo.', 0, 'muy suave', 60, 90, 'Reducir a paseo si el sabado pesa.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-05/README.md'),
(10601, 106, '2026-06-08', 'Lunes', 1, 'activacion', 'Abrir con soltura y margen.', 'Paseo 45-60 minutos o descanso activo.', 'Movilidad 10 minutos.', 'Si la semana 05 dejo fatiga, convertir en descanso total.', 0, 'muy suave', 45, 60, 'Descanso total si hay fatiga.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'),
(10602, 106, '2026-06-09', 'Martes', 2, 'referencia-aerobica', 'Repetir la referencia aerobica y comparar sensaciones.', 'Bicicleta Z2 estable 60-90 minutos en formato comparable al de la semana 03.', 'Registrar potencia media, frecuencia cardiaca media y sensacion.', 'No buscar mejor dato a la fuerza; importa la estabilidad.', 1, 'suave', 60, 90, 'Priorizar comparabilidad.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'),
(10603, 106, '2026-06-10', 'Miercoles', 3, 'fuerza', 'Mantener fuerza minima dentro de la semana tipo.', 'Rutina base de fuerza 30-40 minutos.', 'Paseo suave 20 minutos opcional.', 'Mejor quedarse corto que interferir con jueves o sabado.', 0, 'moderada', 30, 40, 'Reducir si interfiere con los dias clave.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'),
(10604, 106, '2026-06-11', 'Jueves', 4, 'bicicleta-z2', 'Sumar un segundo dia aerobico util y comodo.', 'Bicicleta Z2 75-90 minutos.', 'Movilidad o core suave 10 minutos.', 'Dia pensado para confirmar normalidad, no crecimiento.', 0, 'suave', 75, 90, 'Mantener comodo.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'),
(10605, 106, '2026-06-12', 'Viernes', 5, 'recuperacion', 'Llegar fresco al ultimo dia clave del bloque.', 'Bicicleta muy facil 45 minutos o paseo.', 'Estiramientos suaves.', 'Dia muy facil sin excepciones.', 0, 'muy suave', 45, 45, 'No anadir carga.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'),
(10606, 106, '2026-06-13', 'Sabado', 6, 'salida-larga', 'Repetir salida larga controlada con buena sensacion final.', 'Bicicleta 2h45-3h en Z2.', 'Nutricion e hidratacion ordenadas.', 'El mejor cierre es acabar con ganas de volver a hacerlo.', 1, 'suave', 165, 180, 'Recortar si aparece deuda clara.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md'),
(10607, 106, '2026-06-14', 'Domingo', 7, 'complementaria', 'Cerrar B1 leyendo si la semana se puede repetir.', 'Paseo largo, monte suave o bicicleta facil 60-75 minutos.', 'Revision completa del bloque y decision sobre paso a B2.', 'Si hay cansancio no previsto, simplificar y anotar que B1 necesita una semana extra.', 0, 'muy suave', 60, 75, 'Simplificar si hay cansancio no previsto.', '2026/Bloques/B1-Reconstruccion-solida/Semanas/Semana-06/README.md');