INSERT INTO plan_micro_weeks (
    week_id,
    block_id,
    week_code,
    sequence_in_block,
    start_date,
    end_date,
    week_role,
    entry_state,
    objective_primary,
    objective_secondary,
    key_risk,
    weight_goal,
    target_volume_hours_min,
    target_volume_hours_max,
    key_days,
    support_days,
    closure_rule,
    markdown_path
) VALUES (
    201,
    2,
    'Semana-01',
    1,
    '2026-06-15',
    '2026-06-21',
    'Reentrada absorbente',
    'Salida de B1 con base util pero con deuda reciente de densidad.',
    'Restaurar margen funcional manteniendo la bicicleta como eje.',
    'Sostener frecuencia alta sin permitir que los dias de soporte crezcan por inercia.',
    'Interpretar la buena respuesta tecnica reciente como permiso para volver a acumular desde el primer dia.',
    'Estabilizar el proceso y no buscar mas descenso a corto plazo.',
    5.0,
    6.0,
    '2 dias aerobicos comodos al inicio de la semana.',
    'Lunes muy facil, miercoles ligero y cierre completo de descanso por viaje.',
    'Solo crecer si el descanso de viernes a domingo se traduce en mejor frescura real, no solo en ganas de entrenar.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
)
ON CONFLICT(week_id) DO UPDATE SET
    block_id = excluded.block_id,
    week_code = excluded.week_code,
    sequence_in_block = excluded.sequence_in_block,
    start_date = excluded.start_date,
    end_date = excluded.end_date,
    week_role = excluded.week_role,
    entry_state = excluded.entry_state,
    objective_primary = excluded.objective_primary,
    objective_secondary = excluded.objective_secondary,
    key_risk = excluded.key_risk,
    weight_goal = excluded.weight_goal,
    target_volume_hours_min = excluded.target_volume_hours_min,
    target_volume_hours_max = excluded.target_volume_hours_max,
    key_days = excluded.key_days,
    support_days = excluded.support_days,
    closure_rule = excluded.closure_rule,
    markdown_path = excluded.markdown_path;

INSERT INTO plan_planned_sessions (
    planned_session_id,
    week_id,
    session_date,
    day_name,
    sequence_in_week,
    planned_role,
    planned_type,
    objective,
    primary_session,
    complementary_session,
    notes,
    is_key_session,
    intensity_class,
    duration_min,
    duration_max,
    adjustment_rule,
    markdown_path
) VALUES
(
    20101,
    201,
    '2026-06-15',
    'Lunes',
    1,
    'recuperacion',
    'recuperacion',
    'Abrir con soltura real tras el fin de semana de cierre de B1.',
    'Paseo 60-120 minutos, bicicleta Z1 60-120 minutos o descanso activo.',
    'Pecho, triceps y hombro 25-30 minutos.',
    'Si el domingo aun pesa, convertir el dia en descanso casi total; incluso en el extremo alto debe seguir siendo claramente regenerativa.',
    0,
    'muy suave',
    60,
    120,
    'No anadir carga si el cuerpo sigue pesado; incluso en el extremo alto la sesion debe seguir siendo claramente regenerativa.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
),
(
    20102,
    201,
    '2026-06-16',
    'Martes',
    2,
    'resistencia-aerobica-principal',
    'referencia-aerobica',
    'Recuperar una referencia aerobica comoda sin ambicion de crecimiento.',
    'Bicicleta Z2 120-130 minutos, estable y comparable.',
    'Espalda y biceps 25-30 minutos.',
    'Si el pulso sale alto o las piernas estan opacas, recortar al extremo bajo.',
    1,
    'suave',
    120,
    130,
    'Priorizar comparabilidad y control global de la sesion.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
),
(
    20103,
    201,
    '2026-06-17',
    'Miercoles',
    3,
    'resistencia-aerobica-suave',
    'complementaria',
    'Sostener movimiento facil y trabajo de core sin generar residuo.',
    'Paseo 20-40 minutos o descanso activo.',
    'Core 25-30 minutos.',
    'Dia claramente ligero; no compensar con volumen escondido.',
    0,
    'muy suave',
    20,
    40,
    'Reducir a solo movilidad o descanso activo si el martes deja coste raro.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
),
(
    20104,
    201,
    '2026-06-18',
    'Jueves',
    4,
    'resistencia-aerobica-principal',
    'bicicleta-z2',
    'Repetir un segundo dia aerobico util con buena sensacion.',
    'Bicicleta Z2 120-130 minutos.',
    'Pecho, triceps y hombro 25-30 minutos.',
    'Importa salir comodo y acabar mejor que el miercoles, no mas cansado.',
    1,
    'suave',
    120,
    130,
    'Mantener una ejecucion comoda y globalmente aerobica.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
),
(
    20105,
    201,
    '2026-06-19',
    'Viernes',
    5,
    'descanso',
    'descanso',
    'Empezar el tramo de viaje convirtiendolo en descanso real.',
    'Descanso.',
    NULL,
    'Solo movilidad minima si el viaje lo pide; no convertir el dia en activacion encubierta.',
    0,
    'descanso',
    0,
    0,
    'No compensar con carga antes o despues.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
),
(
    20106,
    201,
    '2026-06-20',
    'Sabado',
    6,
    'descanso',
    'descanso',
    'Aprovechar la indisponibilidad para consolidar absorcion y bajar carga aguda.',
    'Descanso.',
    NULL,
    'Priorizar descanso, hidratacion y regularidad basica; no buscar compensaciones antes o despues.',
    0,
    'descanso',
    0,
    0,
    'Mantener descanso completo.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
),
(
    20107,
    201,
    '2026-06-21',
    'Domingo',
    7,
    'descanso',
    'descanso',
    'Cerrar la semana dejando que el descanso haga su trabajo.',
    'Descanso.',
    'Hidratacion, movilidad ligera si apetece y revision semanal, sin fuerza.',
    'El exito no es sumar minutos sino llegar al lunes siguiente con mejor sensacion que al entrar en la semana.',
    0,
    'descanso',
    0,
    0,
    'Mantener el descanso como parte activa de la absorcion.',
    '2026/Bloques/B2-Construccion-aerobica-extensiva-I/Semanas/Semana-01/README.md'
)
ON CONFLICT(planned_session_id) DO UPDATE SET
    week_id = excluded.week_id,
    session_date = excluded.session_date,
    day_name = excluded.day_name,
    sequence_in_week = excluded.sequence_in_week,
    planned_role = excluded.planned_role,
    planned_type = excluded.planned_type,
    objective = excluded.objective,
    primary_session = excluded.primary_session,
    complementary_session = excluded.complementary_session,
    notes = excluded.notes,
    is_key_session = excluded.is_key_session,
    intensity_class = excluded.intensity_class,
    duration_min = excluded.duration_min,
    duration_max = excluded.duration_max,
    adjustment_rule = excluded.adjustment_rule,
    markdown_path = excluded.markdown_path;

INSERT INTO plan_session_zone_targets (
    planned_zone_target_id,
    planned_session_id,
    target_basis,
    target_kind,
    source_kind,
    source_text,
    comparison_eligibility
) VALUES
(
    20,
    20102,
    'heart_rate',
    'single_zone',
    'derived',
    'Bicicleta Z2 120-130 minutos, estable y comparable.',
    'eligible'
),
(
    21,
    20104,
    'heart_rate',
    'single_zone',
    'derived',
    'Bicicleta Z2 120-130 minutos.',
    'eligible'
)
ON CONFLICT(planned_session_id) DO UPDATE SET
    target_basis = excluded.target_basis,
    target_kind = excluded.target_kind,
    source_kind = excluded.source_kind,
    source_text = excluded.source_text,
    comparison_eligibility = excluded.comparison_eligibility;

INSERT INTO plan_session_zone_segments (
    planned_zone_target_id,
    sequence_order,
    segment_label,
    target_zone_min_code,
    target_zone_max_code,
    target_duration_seconds_min,
    target_duration_seconds_max,
    notes
) VALUES
(
    20,
    1,
    'Derived target',
    'Z2',
    'Z2',
    NULL,
    NULL,
    'Sesion globalmente aerobica con Z2 como techo funcional.'
),
(
    21,
    1,
    'Derived target',
    'Z2',
    'Z2',
    NULL,
    NULL,
    'Sesion globalmente aerobica con Z2 como techo funcional.'
)
ON CONFLICT(planned_zone_target_id, sequence_order) DO UPDATE SET
    segment_label = excluded.segment_label,
    target_zone_min_code = excluded.target_zone_min_code,
    target_zone_max_code = excluded.target_zone_max_code,
    target_duration_seconds_min = excluded.target_duration_seconds_min,
    target_duration_seconds_max = excluded.target_duration_seconds_max,
    notes = excluded.notes;